version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personas_db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=personas_db
      - DB_USER=user
      - DB_PASS=password
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh  # Montamos el script en el contenedor
    command: ["sh", "/wait-for-it.sh", "db:5432", "--", "python", "app.py"]  # Esperamos a que la DB esté disponible

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

volumes:
  dbdata:
