version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["sh", "/wait-for-it.sh", "db:5432", "--", "python", "app.py"]

  frontend:
    image: nginx:alpine
    ports:
      - "8443:443"  # HTTPS en puerto 8443
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"  # Accede a Adminer en http://localhost:8082

volumes:
  dbdata:
